### ISSUE TITLE
V2 amber format causes linter errors when using "files.associations"

### ISSUE THREAD

**Issue by noahnu** [syrupy-project/syrupy#598]
I just spent a few minutes upgrading, but by adding `"*.ambr": "python"` to `"files.associations"`, vscode's languge server (pylance) really starts throwing a fit about all the syntax issues since these aren't meant to be valid python. @noahnu, do you have any suggestions on how to get language highlighting, without linting? A `# type: ignore` comment works, but that's an edit to the snapshot, and a path I think we generally don't want to go down. I tried `"python.linting.ignorePatterns"`, but it didn't seem to have any effect. 

The other idea I had was to set the language to something that parses amber _well enough_, that I don't have a language server for. Perl, Julia, Ruby, and Coffeescript all work well enough.

_Originally posted by @zevisert in https://github.com/tophat/syrupy/pull/575#issuecomment-1104550053_

**Comment by noahnu** [comment]
I have an old repo where I attempted a custom vscode language extension. I think it'd make sense to update that and get it working.

**Comment by zevisert** [comment]
Hmm. Thanks for the reply, I'll come back here if I figure out what's up with `"python.linting.ignorePatterns"`. With how much configuration we have in vscode now, I'm surprised that we can't have syntax highlighting without using a LSP!

**Comment by zevisert** [comment]
Also, I'm laughing at the _reference in new issue_'s title. Had I just made an issue, I would have called it something like 
> "V2 amber format causes linter errors when using `"files.associations"`"

**Comment by noahnu** [comment]
I used the "reference in new issue" button from the GitHub app on my phone :)

**Comment by noahnu** [comment]
Is this still an issue? I believe the latest changes to the amber serializer plays a bit nicer with python syntax highlighting.

**Comment by zevisert** [comment]
Syntax highlighting as python with vscode's `files.associations": { "*.ambr": "python", }` works well enough with the new format, but we've stuck with using `"*ambr": "coffeescript"` because marking them as python enables linting, and there's still all sorts of things that a linter would pick up if snapshots were meant to be linted. 

I know that they're not meant to be linted, so what I'm looking for is a good syntax highlighter for snapshots to improve readability, without marking all of my snapshots as problems in my workspace because the linter is complaining about indentation or class type snapshots, eg:

```python
# name: test_example_snapshot
  dict({                                 # Unexpected Indentation
    'id': <class 'uuid.UUID'>,           # Invalid syntax | Expected Expression
    'ok': False
  })
# ---                                    # No new line at end of file
```

This is a perfectly valid snapshot, but treating it with vscode's python syntax highlighting also brings all of these linter problems. Using something unrelated to the project like Julia, Ruby, Perl, or Coffeescript as the syntax highlighter probably means no linters are installed, so the snapshots get syntax highlighting without also reporting linting problems.

It would be great if I could say `*.ambr` files are to be highlighted as Syrupy's Amber instead of relying on another language's grammar. Really, I guess I'm asking for a textmate grammar to highlight snapshots with.

**Comment by noahnu** [comment]
See previous comment -- open to a community plugin with credit in the README.

**Comment by zevisert** [comment]
Coming back around to this; you can usually tell your editor to not lint certain files. For vscode that'd be 
```jsonc
{
  "files.associations": {
    // ambr files are pypi.org/project/syrupy snapshots, they're not actually python, but
    // they follow a similar grammar which helps when viewing to see some syntax highlighting.
    "*.ambr": "python"
  },
  "mypy-type-checker.ignorePatterns": ["*.ambr"],
  "python.analysis.exclude": ["*.ambr"],
}
```

This has been totally sufficient for my team and I. Any kind of editor plugin effort would need to provide more features than just syntax highlighting. Maybe back linking back to the test when viewing the snapshots, but that's something that should go in a new issue :)
